apiVersion: v1
kind: Service
metadata:
  name: k8sspringdemo
  namespace: k8sspringdemo
  labels:
    app: k8sspringdemo
spec:
  selector:
    app: k8sspringdemo
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
