apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8sspringdemo
  namespace: k8sspringdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8sspringdemo
      version: 'v1'
  template:
    metadata:
      labels:
        app: k8sspringdemo
        version: 'v1'
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - k8sspringdemo
                topologyKey: kubernetes.io/hostname
              weight: 100
      initContainers:
        - name: init-ds
          image: busybox:latest
          command:
            - '/bin/sh'
            - '-c'
            - |
              while true
              do
                rt=$(nc -z -w 1 k8sspringdemo-postgresql 5432)
                if [ $? -eq 0 ]; then
                  echo "DB is UP"
                  break
                fi
                echo "DB is not yet reachable;sleep for 10s before retry"
                sleep 10
              done
      containers:
        - name: k8sspringdemo-app
          image: locahost:5001/k8sspringdemo
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: JHIPSTER_SECURITY_AUTHENTICATION_JWT_BASE64_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: secret
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://k8sspringdemo-postgresql.k8sspringdemo.svc.cluster.local:5432/k8SSpringDemo
            - name: SPRING_DATASOURCE_USERNAME
              value: k8SSpringDemo
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: k8sspringdemo-postgresql
                  key: postgresql-password
            - name: SPRING_LIQUIBASE_URL
              value: jdbc:postgresql://k8sspringdemo-postgresql.k8sspringdemo.svc.cluster.local:5432/k8sspringdemo
            - name: MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED
              value: 'true'
            - name: JAVA_OPTS
              value: ' -Xmx256m -Xms256m'
            - name: SERVER_SHUTDOWN
              value: graceful
          resources:
            requests:
              memory: '512Mi'
              cpu: '500m'
            limits:
              memory: '1Gi'
              cpu: '1'
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /management/health/readiness
              port: http
            initialDelaySeconds: 20
            periodSeconds: 15
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /management/health/liveness
              port: http
            initialDelaySeconds: 120
