apiVersion: v1
kind: Secret
metadata:
  name: k8sspringdemo-postgresql
  namespace: k8sspringdemo
  labels:
    app: k8sspringdemo-postgresql
type: Opaque
data:
  postgresql-password: OWM5MjcwMjExMmI3YTQyNjkwMTdiYTJhZGVmNDg5ZDE4N2IzYjNiMjQ3ZTA4Mjc3NDU5OWFkY2NjZTY1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8sspringdemo-postgresql
  namespace: k8sspringdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8sspringdemo-postgresql
  template:
    metadata:
      labels:
        app: k8sspringdemo-postgresql
    spec:
      volumes:
        - name: data
          emptyDir: {}
      containers:
        - name: postgres
          image: postgres:16.4
          env:
            - name: POSTGRES_USER
              value: k8SSpringDemo
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: k8sspringdemo-postgresql
                  key: postgresql-password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          resources:
            requests:
              memory: '512Mi'
              cpu: '500m'
            limits:
              memory: '1Gi'
              cpu: '1'
---
apiVersion: v1
kind: Service
metadata:
  name: k8sspringdemo-postgresql
  namespace: k8sspringdemo
spec:
  selector:
    app: k8sspringdemo-postgresql
  ports:
    - port: 5432
