apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: localhost:5001/k8sspringdemo
      context: ../../k8sSpringDemo
      jib: {}
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:latest'
deploy:
  kustomize: {}
